Controllers/AdminController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models;
using Models.AdminModel;

namespace Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly IWebHostEnvironment _WebHostEnvironment;

        public AdminController(ApplicationContext context, IWebHostEnvironment WebHostEnvironment)
        {
            _context = context;
            _WebHostEnvironment = WebHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.CompanySettingsDB.ToListAsync());
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AdminViewModel vm)
        {
            string FileName = UploadFile(vm);
            var models = new CompanySetting
            {
                CompanyName = vm.CompanyName,
                Address = vm.Address,
                PhoneNumber = vm.PhoneNumber,
                Email = vm.Email,
                Logo = FileName
            };


            if (ModelState.IsValid)
            {
                _context.Add(models);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        ////////////////
        ///image file 
        ///////////////
        private string UploadFile(AdminViewModel vm)
        {
            string fileName = null;

            if (vm.Logo != null)
            {
                string uploadDir = Path.Combine(_WebHostEnvironment.WebRootPath, "images");
                fileName = Guid.NewGuid().ToString() + "-" + vm.Logo.FileName;
                string filePath = Path.Combine(uploadDir, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    vm.Logo.CopyTo(fileStream);
                }
            }
            return fileName;
        }





        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = await _context.CompanySettingsDB.FindAsync(id);

            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var data = _context.CompanySettingsDB.Find(id);
            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, CompanySetting models)
        {
            if (id != models.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(models);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(models);

        }




        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.CompanySettingsDB
                .FirstOrDefaultAsync(m => m.Id == id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var students = await _context.CompanySettingsDB.FindAsync(id);

            //delete image from wwwroot/Imgbannar
            var imgPath = Path.Combine(_WebHostEnvironment.WebRootPath, "images", students.Logo);
            if(System.IO.File.Exists(imgPath))
            System.IO.File.Delete(imgPath);


            _context.CompanySettingsDB.Remove(students);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Admin/Create.cshtml
@model Models.AdminViewModel
@{
    ViewBag.Title = "Create page";
    Layout = "_AdminLayout";
}

<h2 class="text-center">Create</h2>

<form asp-action="Create" class="mt-5" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="CompanyName" class="control-label"></label>
            <input asp-for="CompanyName" class="form-control" required/>
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control"  required/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" required />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Logo"></label>
            <div class="custom-file">
                <input asp-for="Logo" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" required>
                <label class="custom-file-label" for="inputGroupFile01"></label>
            </div>
            <span asp-validation-for="Logo" class="text-danger"></span>
        </div>
    </div>

        <div class="form-group">
            <label asp-for="Address" class="control-label"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input  type="submit" value="Create" class="btn btn-primary btn-sm"> |
            <a asp-action="Index" class="btn btn-secondary btn-sm">Back to list</a>
        </div>
        
</form>

Views/Admin/Delete.cshtml
@model Models.AdminModel.CompanySetting

@{
    ViewBag.Title = "Details page";
    Layout = "_AdminLayout";
}

<h1 class="text-center text-warning">Delete</h1>

<div>
    <h4>Company Setting panel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
        <dt class = "col-sm-2">
            Uploded Logo
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@Model.Logo" alt="img" asp-append-version="true" width="250px" height="250px" />
        </dd>
    </dl>
</div>
<div>
   <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> |
        <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
    </form>
</div>

Views/Admin/Details.cshtml
@model Models.AdminModel.CompanySetting

@{
    ViewBag.Title = "Details page";
}
            <div class="container">
                <div class="card text-center">
                    <div class="card-body">
                        <div class="content mt-3">
                            <h4 class="title font-weight-bold">Logo</h4>
                            <img src="~/images/@Model.Logo" alt="image"  width="200" height="200" asp-append-version="true">
                        </div>
                    </div>
                </div>

                <div class="row d-flex align-items-stretch">
                    <div class="col-md-4">
                        <div class="card text-center">
                            <div class="card-body">
                                <div class="box-icon bg-info-alt text-info d-flex align-items-center justify-content-center">
                                    <i class="las la-phone-volume"></i>
                                </div>
                                <div class="content mt-3">
                                    <h4 class="title font-weight-bold">Phone</h4>
                                    <p class="text-muted">
                                        Start working with Landrick that can provide everything
                                    </p>
                                    <a href="#" class="text-primary">@Html.DisplayFor(model => model.PhoneNumber)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end col-->

                    <div class="col-md-4 mt-4 mt-sm-0 pt-2 pt-sm-0">
                        <div class="card text-center">
                            <div class="card-body">
                                <div class="content mt-3">
                                    <h4 class="title font-weight-bold">Address</h4>
                                    <p class="text-muted">
                                        Start working with Landrick that can provide everything
                                    </p>
                                    <h6>@Html.DisplayFor(model => model.Address)</h6>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 mt-4 mt-sm-0 pt-2 pt-sm-0">
                        <div class="card text-center">
                            <div class="card-body">
                                <div class="box-icon bg-warning-alt text-warning d-flex align-items-center justify-content-center">
                                    <i class="las la-envelope-open"></i>
                                </div>
                                <div class="content mt-3">
                                    <h4 class="title font-weight-bold">Email</h4>
                                    <p class="text-muted">
                                        Start working with Landrick that can provide everything
                                    </p>
                                    <a href="#" class="text-primary">@Html.DisplayFor(model => model.Email)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end col-->

                    
                    <!--end col-->
                    @* <div class="col-md-3 mt-4 mt-sm-0 pt-2 pt-sm-0">
                        <div class="card text-center">
                            <div class="card-body">
                                <div class="box-icon bg-success-alt text-success d-flex align-items-center justify-content-center">
                                    <i class="las la-street-view"></i>
                                </div>
                                <div class="content mt-3">
                                    <h4 class="title font-weight-bold">Street view</h4>
                                    <p class="text-muted">
                                        Start working with Landrick that can provide everything
                                    </p>
                                    <a href="#" class="text-primary">View on map</a>
                                </div>
                            </div>
                        </div>
                    </div> *@
                    <!--end col-->
                </div>
                <!--end row-->
            </div>

@* <h1 class="text-center text-warning">Details</h1>

<div>
    <h4>Company Setting panel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-info btn-sm">Update</a> |
    <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
</div>
 *@

Views/Admin/Edit.cshtml
@model Models.AdminModel.CompanySetting
@{
    ViewBag.Title = "Edit page";
    Layout = "_AdminLayout";
}

<h2 class="text-center">Edit</h2>

<form asp-action="Edit" class="mt-5">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="CompanyName" class="control-label"></label>
            <input asp-for="CompanyName" class="form-control" />
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control"  />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
        <div class="form-group">
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        @* <div class="form-group col-md-6">
            <label asp-for="Logo"></label>
            <div class="custom-file">
                <input asp-for="Logo" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
            </div>
            <span asp-validation-for="Logo" class="text-danger"></span>
        </div> *@

        <div class="form-group">
            <label asp-for="Address" class="control-label"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input  type="submit" value="Save" class="btn btn-primary btn-sm"> |
            <a asp-action="Index" class="btn btn-secondary btn-sm">Back to list</a>
        </div>
        
</form>

Views/Admin/Index.cshtml
@model IEnumerable<Models.AdminModel.CompanySetting>
@{
    ViewBag.Title = "Admin page";
    Layout = "_AdminLayout";
}

<h1 class="text-center">Company setting</h1>
<div class="text-center">
    <a asp-controller="Admin" asp-action="Create" class="btn btn-success btn-sm">Create New</a>
</div>


<table class="table table-bordered table-hover mt-5">
    <thead>
        <tr>
            <th>
                Edit
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logo)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
    {
        <tr>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Update</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <img src="~/images/@item.Logo" alt="image" class="rounded-circle" width="40" height="40" asp-append-version="true">
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">Details</a>   
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>