Models/AdminModel/Bannar.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace Models.AdminModel
{
    public class Bannar
    {
        [Key]
        public int Id { get; set; }
        public string Heading { get; set; }
        public string SubTitle { get; set; }

        [DisplayName("Image")]
        public string Image { get; set; }
        
        [NotMapped]
        [DisplayName("Upload file")]
        public IFormFile ImageFile { get; set; }
    }
}

Controllers/BannarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using Models.AdminModel;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace Adminpanel.Controllers
{
    public class BannarController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly IWebHostEnvironment _WebHostEnvironment;

        public BannarController(ApplicationContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _WebHostEnvironment = webHostEnvironment;
        }

        // GET: Bannar
        public async Task<IActionResult> Index()
        {
            return View(await _context.BannarDB.ToListAsync());
        }

        // GET: Bannar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bannar = await _context.BannarDB
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bannar == null)
            {
                return NotFound();
            }

            return View(bannar);
        }

        // GET: Bannar/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bannar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Heading,SubTitle,ImageFile")] Bannar bannar)
        {
            if (ModelState.IsValid)
            {
                //Save image to wwwroot/imgBannar
                string wwwRootPath = _WebHostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(bannar.ImageFile.FileName);
                string extension = Path.GetExtension(bannar.ImageFile.FileName);
                bannar.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;

                string path = Path.Combine(wwwRootPath + "/ImgBannar/", fileName);
                using (var filestream = new FileStream(path, FileMode.Create))
                {
                    await bannar.ImageFile.CopyToAsync(filestream);
                }

                //Insert record

                _context.Add(bannar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bannar);
        }

        // GET: Bannar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bannar = await _context.BannarDB.FindAsync(id);
            if (bannar == null)
            {
                return NotFound();
            }
            return View(bannar);
        }

        // POST: Bannar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Heading,SubTitle,Image")] Bannar bannar)
        {
            if (id != bannar.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bannar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BannarExists(bannar.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bannar);
        }

        // GET: Bannar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bannar = await _context.BannarDB
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bannar == null)
            {
                return NotFound();
            }

            return View(bannar);
        }

        // POST: Bannar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bannar = await _context.BannarDB.FindAsync(id);

            //delete image from wwwroot/Imgbannar
            var imgPath = Path.Combine(_WebHostEnvironment.WebRootPath, "ImgBannar", bannar.Image);
            if(System.IO.File.Exists(imgPath))
            System.IO.File.Delete(imgPath);
            
            _context.BannarDB.Remove(bannar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BannarExists(int id)
        {
            return _context.BannarDB.Any(e => e.Id == id);
        }
    }
}

Views/Bannar/Create.cshtml
@model Models.AdminModel.Bannar

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Create</h1>

<h4>Bannar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Heading" class="control-label"></label>
                <input asp-for="Heading" class="form-control" required/>
                <span asp-validation-for="Heading" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubTitle" class="control-label"></label>
                <input asp-for="SubTitle" class="form-control" required/>
                <span asp-validation-for="SubTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" accept="image/*" required/>
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Bannar/Delete.cshtml
@model Models.AdminModel.Bannar

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-center">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bannar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Heading)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Heading)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            Uploded Image
        </dt>
        <dd class = "col-sm-10">
            <img src="~/ImgBannar/@Model.Image" alt="img" asp-append-version="true" width="250px" height="250px" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger btn-sm" /> |
        <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
    </form>
</div>

Views/Bannar/Details.cshtml
@model Models.AdminModel.Bannar

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <div class="row d-flex justify-content-between align-items-center">
        <div class="col-md-8">
            <h1 class="intro-title display-4">@Model.Heading</h1>
            <p class="lead display-5">@Model.SubTitle</p>

            <div class="row">
                <div class="col-md-7">
                    <form >
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Search assets ..." aria-label="search" aria-describedby="basic-addon2" />
                                            
                            <div class="input-group-append">
                                <button class="btn btn-primary">Search</button>
                            </div>
                        </div>
                    </form>
				</div>
            </div>
        </div>
        <div class="col-md-4">
            <img src="~/ImgBannar/@Model.Image" asp-append-version="true" width="300px" height="300px" alt="">
        </div>
    </div>
</div>

@* <div>
    <h4>Bannar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Heading)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Heading)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div> *@

Views/Bannar/Edit.cshtml
@model Models.AdminModel.Bannar

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Edit</h1>

<h4>Bannar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Heading" class="control-label"></label>
                <input asp-for="Heading" class="form-control" />
                <span asp-validation-for="Heading" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubTitle" class="control-label"></label>
                <input asp-for="SubTitle" class="form-control" />
                <span asp-validation-for="SubTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary btn-sm">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Bannar/Index.cshtml
@model IEnumerable<Models.AdminModel.Bannar>

@{
    ViewData["Title"] = "Index";
    Layout = "_AdminLayout";
}

@* @foreach (var item in Model){
    <div class="float-left ">
        <h1>@item.Heading</h1>

        <h2>@item.SubTitle</h2>

        <img src="~/ImgBannar/@item.Image" asp-append-version="true" width="250px" height="250px" alt="">
        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success btn-sm">Edit</a> 
        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info btn-sm">Details</a>
        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm">Delete</a>
    </div>
} *@


<h1 class="text-center">Bannar page</h1>
<div class="text-center">
    <a asp-controller="Bannar" asp-action="Create" class="btn btn-success btn-sm">Create New</a>
</div>
<table class="table table-bordered table-hover mt-5">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Heading)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubTitle)
            </td>
            <td>
                <img src="~/ImgBannar/@item.Image" alt="image" class="rounded-circle" width="40" height="40" asp-append-version="true">
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>